name: .NET CI

on:
  push:
    branches: [ "test-ci" ]
  pull_request:
    branches: [ "test-ci" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # --- Backend build ---
    - name: Restore dependencies (Backend)
      run: dotnet restore ./backend/srtk/srtk.sln

    - name: Build Backend
      run: dotnet build ./backend/srtk/srtk.sln --configuration Release --no-restore

    # --- Tests build ---
    - name: Restore dependencies (Tests)
      run: dotnet restore ./backend/tests/srtk.tests/srtk.tests.sln

    - name: Build Tests
      run: dotnet build ./backend/tests/srtk.tests/srtk.tests.sln --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test ./backend/tests/srtk.tests/srtk.tests.sln --no-build --verbosity normal
